name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: ZenWave360/release-workflows/.github/workflows/main-gradle.yml@main
    with:
      java-version: "21"
      kover-xml-files: "./manifest-core/build/reports/kover/report.xml"
